### ISSUE TITLE
Authoring Gap Analysis

### ISSUE THREAD

**Issue by shervinafshar** [w3c/alreq#157]
https://github.com/shervinafshar/typography/tree/gh-pages/gap-analysis

**Comment by shervinafshar** [comment]
Ongoing is the gap analysis for justification, numerals, and drop-caps. Drop-caps and justifications need minor changes needed. @r12a is going to provide some notes on numerals text.

**Comment by shervinafshar** [comment]
Coming up for next meeting would:
* Cursive text
* Text boundaries and selection

**Comment by shervinafshar** [comment]
Added three separate PRs to isolate any needed changes if need be:
* [Numerals](https://github.com/w3c/typography/pull/58);
* [Dropcaps](https://github.com/w3c/typography/pull/57);
* [Justification](https://github.com/w3c/typography/pull/56).

**Comment by r12a** [comment]
@shervinafshar @behnam you will have seen that i have been developing a document format for capturing gap analysis information.  I needed to do this for other upcoming work, so i experimented with the arabic information to develop the format.  This is what i came up with: https://w3c.github.io/alreq/gap-analysis/

Once we get that document to a certain point, we should be able to make a WD, and eventually a WG Note.  This format is much more robust and easier to maintain that the one we were using before.

Do you think it looks ok?  Shervin, would you be happy to make your edits to this  document going forward?  (A quick response would be appreciated, since i need to make a template available for others.)

**Comment by shervinafshar** [comment]
Sure. Sounds good to me.

**Comment by r12a** [comment]
Great. Thanks for the quick response. Unless @behnam has any objections, i suggest then that you start making your edits to that document now. I'll do the same for my edits.

**Comment by r12a** [comment]
(Btw, fwiw, the quick draft for Hindi/Marathi at https://w3c.github.io/iip/gap-analysis/deva-hi-mr may give you some more ideas about how i envisaged these documents to look,  although that's still very brief compared to what it could be - i did it just with what was to hand in about an hour.)

**Comment by behnam** [comment]
Thanks, @r12a. It looks much better now! Also, it's great to have it in `alreq` repo, making it easier to review PRs and works on the topics.

**Comment by ntounsi** [comment]
Thanks @r12a. I've been confused for a while about what (and where) @shervinafshar is authoring. The only document I knew was http://w3c.github.io/typography/gap-analysis/. 
Now it looks better to me.
A first question: should this document also include current browsers support (or differences) for needed features? In addition to support in relevant specifications of course. (I think yes).

**Comment by r12a** [comment]
@ntounsi yes, the gap-analysis doc should describe current browser (and ereader) support, or it should point to test results (we have a good few of those at https://www.org/International/tests/), in addition to mentioning spec support.
