### ISSUE TITLE
Structure of the document

### ISSUE THREAD

**Issue by TitusNemeth** [w3c/alreq#211]
Following up from my last PR, I reviewed again the structure of the document and found some items that could possibly be arranged more fittingly. Below is a suggested draft TOC for discussion. 

I have generally sought to follow as much as possible Richard's template here https://w3c.github.io/typography/
One general remark is that in ALREQ we have a sometimes exaggerated use of subsections, which could be folded into the paragraph one hierarchy further up. I have done this with the sub-subsections of the introduction, but I think it could be done elsewhere too. I don't think this number of levels always contributes to improved clarity.

The main change that I've introduced is the reorganisation of the 'Arabic Script Overview', which I have renamed as 'Characteristics of the Arabic script'. Here I have renamed the section 'Typography' as 'Fundamental principles' (where some things should still be added), because its subsections are not typographic, but relate to features of the script. Also the section 'Fonts' does not belong to a description of the script per se, but should be discussed elsewhere – here I have followed Richard's template document and sorted them under 'Characters & phrases'. 

Finally I have introduced a section 'Typography', which is what Richard's document calls 'Layout and pages'. Since layout also includes image placement and everything related to that, I felt that it would be better to stick to 'Typography' when discussing just text organisation. The subsection 'Considerations for mixed-script text' should probably be put here, and merits fleshing out.

I am sure there may be other sections or subsections that could be shifted, but I'll leave it at this for the moment so that things remain manageable.

1.	Introduction
1.1.	Gap Analysis
1.2.	Other Related Resources
1.3.	Language limitation

2.	Characteristics of the Arabic script
2.1.	Fundamental principles
2.1.1.	Multi-level baselines
2.1.2.	Multi-context joining
2.1.3.	Words as groups of letters
2.1.4.	Vertical joining
2.1.5.	The so-called teeth letters
2.2.	The Islamic manuscript tradition
2.2.1.	Origins
2.2.2.	Writing Styles

3.	Characters & phrases
3.1.	Characters & encoding
3.2.	Fonts
3.3.	Direction
3.4.	Joining
3.4.1.	Joining Forms
3.4.2.	Joining Categories
3.4.3.	Joining Rules
3.4.4.	Joining Control
3.4.4.1.	Disjoining Enforcement
3.4.4.2.	Joining Enforcement
3.4.4.3.	Joining-Disjoining Enforcement
3.4.4.4.	Context-Based Joining
3.4.5.	Joining Segments
3.4.5.1.	Closed Joining Segments
3.4.5.2.	Open Joining Segments
3.4.6.	Non-Joining Characters
3.5.	Text Segmentation
3.6.	Positioning diacritics relative to base characters
3.7.	Letter-spacing
3.8.	Special requirements when dealing with cursive glyphs
3.8.1.	Joining and Intra-Word Spaces
3.8.2.	Transparency
3.8.3.	Text border
3.8.4.	Styling individual letters
3.9.	Numbers
3.9.1.	Preferred Terminology
3.9.2.	Families of Numerals
3.9.3.	Formatting of Numerals
3.9.4.	Arabic number in other uses

4.	Lines and paragraphs
4.1.	Line breaking
4.2.	Justification	
4.2.1.	Adjusting Inter-Word Spaces
4.2.2.	Adjusting Intra-Word Spaces
4.2.3.	Alternative Shapes
4.2.4.	Ligatures
4.2.5.	Kashida
4.2.6.	Tatweel
4.2.7.	Combination of the Mechanisms

5.	Typography
5.1.	General text layout and progression
5.2.	Paragraph and line alignment
5.3.	Considerations for mixed-script text
5.4.	Counters, lists, etc
5.5.	Special cases
5.5.1.	Vertical text
5.5.1.1.	Arabic embedded in vertically orientated text
5.5.1.2.	Upright vertical Arabic text

Appendices
A. Characters
A.1 Alphabetical characters
A.2 Diacritics
A.3 Numeral characters
A.4 Punctuations and symbols
A.5 Control characters
B. Glossary

**Comment by r12a** [comment]
I think this is a good start.   Here is a proposal that builds on this, with differences explained below.

1.	Introduction
1.1.	Gap Analysis
1.2.	Other Related Resources
1.3.	Language limitation

2.	Characteristics of the Arabic script
2.1.	Fundamental principles
2.1.1.	Multi-level baselines
2.1.2.	Multi-context joining
2.1.3.	Words as groups of letters
2.1.4.	Vertical joining
2.1.5.	The so-called teeth letters
2.2.	The Islamic manuscript tradition
2.2.1.	Origins
2.2.2.	Writing Styles

3.	Characters & phrases
3.1.	Characters & encoding
3.2.	Fonts
3.2.1.	Ligatures
3.2.2.	Diacritics
3.2.3.	Positioning diacritics relative to base characters
3.3.	Direction
3.3.1.	Vertical text
3.3.2.	Arabic embedded in vertically orientated text
3.3.3.	Upright vertical Arabic text
3.4.	Joining
3.4.1.	Joining Forms
3.4.2.	Joining Categories
3.4.3.	Joining Rules
3.4.4.	Joining Control
3.4.4.1.	Disjoining Enforcement
3.4.4.2.	Joining Enforcement
3.4.4.3.	Joining-Disjoining Enforcement
3.4.4.4.	Context-Based Joining
3.4.5.	Joining Segments
3.4.5.1.	Closed Joining Segments
3.4.5.2.	Open Joining Segments
3.4.6.	Non-Joining Characters
3.4.7.	Special requirements when dealing with cursive glyphs
3.4.7.1.	Joining and Intra-Word Spaces
3.4.7.2.	Transparency
3.4.7.3.	Text border
3.4.7.4.	Styling individual letters
3.5.	Text Segmentation
3.9.	Numbers
3.9.1.	Preferred Terminology
3.9.2.	Families of Numerals
3.9.3.	Formatting of Numerals
3.9.4.	Arabic number in other uses

4.	Lines and paragraphs
4.1.	Line breaking
4.2.	Justification	
4.2.1.	Adjusting Inter-Word Spaces
4.2.2.	Adjusting Intra-Word Spaces
4.2.3.	Alternative Shapes
4.2.4.	Ligatures
4.2.5.	Kashida
4.2.6.	Tatweel
4.2.7.	Combination of the Mechanisms
4.3.	Letter-spacing
4.4.	Counters, lists, etc

5.	Typography
5.1.	General text layout and progression
5.2.	Paragraph and line alignment
5.3.	Considerations for mixed-script text

Appendices
A. Characters
A.1 Alphabetical characters
A.2 Diacritics
A.3 Numeral characters
A.4 Punctuations and symbols
A.5 Control characters
B. Glossary


I would put 'Ligatures' and 'Diacritics' sections currently under 'Arabic Script Overview' (which you seem to have missed) as subsections under 'Fonts'. Ligatures may be relevant for justification (and we have another section with the same name there), but the general principles are germane to a discussion of glyph shaping and positioning in my mind. The Fonts section seems to be the location for that in the above.  I think 'Positioning diacritics relative to base characters' also belongs there.

'Letter spacing' is very much akin to justification, and so i moved it down. 

'Special requirements when dealing with cursive glyphs' is all related to handling of cursivity, which is introduced in the 'Joining' section, so i propose to keep that material together.

For a long time i wasn't sure where to put 'Counters, lists, etc' - under page layout, as you did, or under line & paragraph layout.  In the end i decided to go for the latter, especially because numbered lists are an aspect of line and paragraph layout, and counters are an aspect of numbered list arrangements.  They are also part of a line-related arrangement when used in chapter titles, running headers, etc. whereas it's the title or the header that are part of the overall page layout.

Finally, the 'Special cases' are all related to text direction, so i moved those up (and removed the empty 'Special cases' heading).

> One general remark is that in ALREQ we have a sometimes exaggerated use of subsections, which could be folded into the paragraph one hierarchy further up.

Headings contribute in a number of ways.  They show at a glance the components and structure of a particular concept.  And as signposting, they allow people to find specific pieces of information quickly. They also provide anchors for links, which it particularly important for these lreq documents, which are typically used as reference material, rather than read end-to-end. (They also help in keeping content authors from waffling and wandering around in their discussions.)  So although i think what you did for the introduction looks ok, i'd be careful about doing the same thing in other parts of the document.

[Btw, fwiw, the organisation of https://w3c.github.io/typography/ is a much simplified version of a way of organising typographic information that i've been working on and refining for quite some time now.  For reference, you can see an example of the original structure at https://r12a.github.io/scripts/arabic/.  I'm able to apply the same basic structure to many different writing systems (see https://r12a.github.io/scripts/#scriptnotes). (Much of these pages is dedicated to character repertoire and encoding topics, and the alreq-type stuff starts around the section 'Numbers, dates, currency, etc.') Anyway, that's just a bit of background about where i'm coming from.]

**Comment by TitusNemeth** [comment]
To me all the additions and emendments make sense, and this structure looks better to me than the current one. So if no one objects, maybe we can implement this and then see how it works with the actual content, rather than just the outline.

**Comment by r12a** [comment]
I propose we leave it just for 2 more days, which will make a week, and if there are still no objections let's do it.

**Comment by r12a** [comment]
Ok. No objections.  @TitusNemeth were you planning to prepare the PR?

**Comment by TitusNemeth** [comment]
I cannot do it this week, but may look into it the following week if it hasn't been done yet.

**Comment by r12a** [comment]
I'll try to find time this week. If i can, i grab the edit token at that point.  This will be a major, document wide set of changes, so anyone else working on the document should let me know in order to avoid conflicts blocking one or other person's work.
