### ISSUE TITLE
Variant letter shapes

### ISSUE THREAD

**Issue by r12a** [w3c/alreq#22]
I believe our character list contains all of the characters ق and ڧ, and the characters ف and ڢ?  Given that each pair represents two visual variants of the same letter, if someone in North Africa wants to use a shape relevant to their region, such as ڢ, is it appropriate to use a separate character, or should one expect the difference to be produced by using a different font?  Same question for the qaf.

Of course, the reason i ask is that spelling the same word in two different ways is not ideal for searching, security (eg. IDNs), etc.

**Comment by khaledhosny** [comment]
I think in the case of the different dot placement of ق and ف, it should have been considered a stylistic variant (since AFAICT, this is was tied to Maghribi variants of the Kufi script), so it seems to me encoding them as different characters is unfortunate (the same can be said about the so called “Farsi” yeh, which is used in Egypt as well, but people can’t use it as it is a different character not usually accessible from common Arabic keyboard layouts and resort to Alef maksura in the final and isolate forms not realising the difference).

Some Magribi fonts use the Maghribi placement of the dots for the ف and ق code points, but I can’t tell if this is the norm in such style of fonts (I have access to only one), I’m not also sure how important/wide spread to want that specific variant in non-Maghribi styles, so I think we might need to answer those two questions first.

**Comment by shervinafshar** [comment]
These characters' appearances in our list is because they are considered
auxiliary for Arabic in CLDR data. I will make sure to mark that in the
charts to avoid confusion. Obviously, there are many other Feh-based
characters we are not listing here.

Both of these characters are legacy dating back to Unicode 1.1. So the
rationales used today for encoding might not apply to them.

The same goes for "Arabic Letter Farsi Yeh".

Is there a keyboard layout issued by a standard national body in Egypt
which includes U+06CC? Has there been any efforts to rectify the characters
missing from the layouts?

**Comment by shervinafshar** [comment]
This was discussed in the meeting and the consensus was to add some text to the document regarding some of these characters being the variants of the same letter.

**Comment by r12a** [comment]
Mostafa working on this.

**Comment by mostafah** [comment]
I’m going to add a note at the bottom of the alphabets table. Are these the only two group that should be mentioned:
- U+0641 ARABIC LETTER FEH (ف) and U+06A2 ARABIC LETTER FEH WITH DOT MOVED BELOW (ڢ)
- U+0642 ARABIC LETTER QAF (ق) and U+06A7 ARABIC LETTER QAF WITH DOT ABOVE (ڧ)

or do we have more?

**Comment by shervinafshar** [comment]
Mostafa is going to go ahead with these two groups for now.
