### ISSUE TITLE
Change the title to reflect that this is Arabic script, not Arabic Language

### ISSUE THREAD

**Issue by r12a** [w3c/alreq#88]
I suggest we change the title to 'Arabic Script Layout Requirements'.

**Comment by behnam** [comment]
+1

(I thought we already agreed on this on one of the early meetings and were going to apply the changes.)

**Comment by shervinafshar** [comment]
As I recall, we talked about it and decided to reflect this very clearly
everywhere in the text and don't change the title. The fact of covering
Arabic script rather than language is clearly stated in first lines of the
abstract and first lines of the introduction in the activity homepage.

If we absolutely need to do this, my preference is to keep it consistent
with other major LReq documents; i.e. "Requirements for Arabic Text Layout".

**Comment by ntounsi** [comment]
+1

Najib

**Comment by behnam** [comment]
@shervinafshar, are you recommending to use "Arabic Text" instead of "Arabic Script"? Can you elaborate on that?

**Comment by shervinafshar** [comment]
@behnam, I'm absolutely against this change as previously explained. Let me elaborate:

* As we all probably know very well, "Arabic" is a language as well as a writing system. "Arabic" language uses "Arabic" writing system (aka "Abjadic Arabic", "أبجدية عربية"). So do Azeri, Baluchi, Kashmiri, Kurdish, Pashto, Persian, Punjabi, Sindhi, Uighur, Urdu, and others;
* We stated this very very very clearly that ALReq is not about "Arabic language". It's about layouting text for Arabic writing system; from [mission statement](http://w3c.github.io/i18n-activity/alreq/#about) of the activity: "*This task force will document requirements for the layout and presentation of text in languages that use the Arabic script...*"; from document abstract "*This document describes requirements for the layout and presentation of text in languages that use the Arabic script when they are used by...*";
* "script" is not a synonym for "writing system". "script" is a subset of a writing system (see Coulmas, Florian. 2003. *Writing systems. An introduction*. Cambridge University Press. pg. 35).

**Questions:**
* What is the rationale of this proposal? @r12a, do you care to elaborate?
* Why "script"? No other of the LReq documents use "script" in their title. [JLReq](https://www.w3.org/TR/2012/NOTE-jlreq-20120403) uses "text", [CLReq](https://www.w3.org/TR/2015/WD-clreq-20150730/) uses "text", Indic and Ethiopic are just plain "Indic Layout Requirements" and "Ethiopic Layout Requirements". 

**Bottomline:**

At the moment with existing information, this change seems to me as controversial, arbitrary, and with minor actual benefit to the quality of the document. If I'm persuaded of the change and there is a consensus that our current title is sub-optimal or misleading, then we can follow JLReq or CLReq example and call it "Requirements for Arabic Text Layout".

**Comment by behnam** [comment]
Okay, now I get your point, @shervinafshar. I agree that "script" has a more narrow meaning in linguistics literature, but I think it does support a wider one in general, making terms like "Latin script" and "Arabic script" well understood by almost any audience.

That said, I don't have any preference about the wording and I'm fine with "Arabic Script", "Arabic Text", "Arabic Writing System", or anything similar. Just that, IMHO, it's better to make it a bit more clear in the title that it's not specific to "Arabic Language", which is a common misunderstanding when only the term "Arabic" is used.

**Comment by r12a** [comment]
Hi @shervinafshar, this arose while i was describing the work to the W3C strategy specialists at our FTF last week. They were all surprised when i talked about Persian, since they took 'Arabic' in the current title to refer to the Arabic language.  They asked that we change it, so that the scope is clearer from the title.

I hear your point about the difference between writing systems and scripts.  I suggested 'Arabic Script Layout Requirements' mainly because it seemed simple, although i do agree with Behnam that it would probably convey the meaning well enough for situations such as the one above.

I'm worried that if we say 'Arabic Text Layout Requirements' that won't be any clearer in the Arabic case. (I think that for Japanese it _is_ pretty clear, and Indic too, because of the natures of those scripts/words.  Note also that we are already planning - since the end of last year - to make a similar change to the Chinese title of clreq, which previously as i understand it, used terminology related to language rather than script. We may also need to change the English title to something like Hanzi Text Layout, to more closely match the Chinese title.)

What would you suggest is the best title, given the ask above?

**Comment by shervinafshar** [comment]
Thanks, @r12a. It's more clear now why this surfaced. I don't think authors of such documents should or even could pack a complete and clear scope of the whole document in the title alone to prevent any surprises like this. The intention has always been that anyone encountering the document; a. is minimally aware of the context of writing systems of the world, b. is aware of the fact that W3C Layout Requirement documents are...well...about *text* layout; c. is eager to *at least* read the first line of the abstract section. 

I have received some impromptu criticisms from some folks in Iran mentioning that, the document indeed needs to be more clear about "خط فارسی" ("Farsi script", "Persian script"). My answer to them has always been that what is called "Farsi script" in Iran is a subset of a larger writing system which is the Arabic Script. 

Some other way of thinking about this problem might be considering those pockets of Arabic writing system which are well-developed enough on their own and independent of the other languages of the family of Arabic writing system, so that they can have their own individual LReq document; then one can call those documents "Arabic Layout Requirements" and "Urdu Layout Requirements" without risking confusing folks. That might also help with recruiting local experts and focusing the efforts in a more selective manner.

In closing, if the editors and members of the activity think that we absolutely need to change the title, here are the suggestions which I consider meeting the minimum required criteria (in descending order of preference):
* Arabic Writing System Layout Requirements
* Text Layout Requirements for Arabic Writing System
* Text Layout Requirements for **The** Arabic Script
* Arabic Script**s** Text Layout Requirements

**Comment by r12a** [comment]
Discussed during telecon. All agreed to use third option above, ie.
Text Layout Requirements for the Arabic Script
